apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app-ctr
          image: shoaibraj07/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.108.18.127"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
